project_id = "faeyekynudyzeotbjfsj"

[functions.generate-dubbing]
verify_jwt = true

[functions.generate-lipsync]
verify_jwt = false

[functions.voice-cloning]
verify_jwt = true

[functions.embed-analytics]
verify_jwt = false