project_id = "edjufyzwjicniycrerde"

[functions.tts]
verify_jwt = false

[functions.transcribe]
verify_jwt = false

[functions.generate-ad]
verify_jwt = false

[functions.prompt-to-video]
verify_jwt = false
