// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'x-client-info': 'axessible-premium-editor@1.0.0'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 2 // Throttle real-time updates to reduce load
    }
  }
});

// Query timeout wrapper to prevent hanging queries
export const queryWithTimeout = async <T>(
  queryPromise: Promise<T>,
  timeoutMs = 10000
): Promise<T> => {
  const timeout = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error('Query timeout - request took too long')), timeoutMs)
  );
  
  return Promise.race([queryPromise, timeout]);
};